#def _t_(a): assert os.path.split(a) == os_path_split(a), (os.path.split(a), os_path_split(a))
#def _t2_(a,n,b): assert b == os_path_split(a,n), (b, os_path_split(a,n), n)
#_t_("a")
#_t_("a/")
#_t_("/a")
#_t_("/a/")
#_t2_("a", -1, ("", "a"))
#_t2_("a/", -1, ("", "a", ""))
#_t2_("/a", -1, ("/", "a"))
#_t2_("/a/", -1, ("/", "a", ""))
#_t2_("/a", -1, ("/", "a"))
#_t2_("/a/b/c", -1, ("/", "a", "b", "c"))
#_t2_("/a/b/c", 2, ("/a", "b", "c"))
