def test_url_os__path_normcase():
  assert_equal(url_os.path.normcase("aAbB"), "aAbB")
def test_url_os__path_isabs():
  assert_equal(url_os.path.isabs("aAbB"), False)
  assert_equal(url_os.path.isabs("/aAbB"), True)
def test_url_os__path_join():
  assert_equal(url_os.path.join("aAbB", "", "/root"), "/root")
  assert_equal(url_os.path.join("aAbB", "rel"), "aAbB/rel")
  assert_equal(url_os.path.join("aAbB", ""), "aAbB/")
  assert_equal(url_os.path.join("aAbB", "", "rel"), "aAbB//rel")
  assert_equal(url_os.path.join("", "rel"), "./rel")
  assert_equal(url_os.path.join("", "rel", "/root"), "/root")
def test_url_os__path_split():
  assert_equal(url_os.path.split("aAbB"), ("", "aAbB"))
  assert_equal(url_os.path.split("/aAbB"), ("/", "aAbB"))
  assert_equal(url_os.path.split("/aAbB/"), ("/aAbB", ""))
  assert_equal(url_os.path.split("/aAbB//"), ("/aAbB/", ""))
  assert_equal(url_os.path.split("/aAbB//rel"), ("/aAbB/", "rel"))
def test_url_os__path_splitext():
  assert_equal(url_os.path.splitext("aAbB"), ("aAbB", ""))
  assert_equal(url_os.path.splitext(".aAbB"), (".aAbB", ""))
  assert_equal(url_os.path.splitext("..aAbB"), ("..aAbB", ""))
  assert_equal(url_os.path.splitext("a.AbB"), ("a", ".AbB"))
  assert_equal(url_os.path.splitext("aAbB."), ("aAbB", "."))
  assert_equal(url_os.path.splitext("aAbB/"), ("aAbB/", ""))
  assert_equal(url_os.path.splitext(".aAbB/"), (".aAbB/", ""))
  assert_equal(url_os.path.splitext("..aAbB/"), ("..aAbB/", ""))
  assert_equal(url_os.path.splitext("a.AbB/"), ("a.AbB/", ""))
  assert_equal(url_os.path.splitext("aAbB./"), ("aAbB./", ""))
  assert_equal(url_os.path.splitext("meow/aAbB"), ("meow/aAbB", ""))
  assert_equal(url_os.path.splitext("meow/.aAbB"), ("meow/.aAbB", ""))
  assert_equal(url_os.path.splitext("meow/..aAbB"), ("meow/..aAbB", ""))
  assert_equal(url_os.path.splitext("meow/a.AbB"), ("meow/a", ".AbB"))
  assert_equal(url_os.path.splitext("meow/aAbB."), ("meow/aAbB", "."))
def test_url_os__path_splitdrive():
  assert_equal(url_os.path.splitdrive("aAbB"), ("", "aAbB"))
  assert_equal(url_os.path.splitdrive("/aAbB"), ("", "/aAbB"))
  assert_equal(url_os.path.splitdrive(""), ("", ""))
def test_url_os__path_basename():
  assert_equal(url_os.path.basename("aAbB"), "aAbB")
  assert_equal(url_os.path.basename("/aAbB"), "aAbB")
  assert_equal(url_os.path.basename("//aAbB"), "aAbB")
  assert_equal(url_os.path.basename("aAbB/"), "")
  assert_equal(url_os.path.basename("aAbB//"), "")
  assert_equal(url_os.path.basename("aAbB//rel"), "rel")
def test_url_os__path_dirname():
  assert_equal(url_os.path.dirname("aAbB"), "")
  assert_equal(url_os.path.dirname("/aAbB"), "/")
  assert_equal(url_os.path.dirname("aAbB/"), "aAbB")
  assert_equal(url_os.path.dirname("aAbB//"), "aAbB/")
  assert_equal(url_os.path.dirname("aAbB//rel"), "aAbB/")
def test_url_os__path_normpath():
  assert_equal(url_os.path.normpath("aAbB"), "aAbB")
  assert_equal(url_os.path.normpath("aAbB/"), "aAbB/")
  assert_equal(url_os.path.normpath("aAbB//"), "aAbB//")
  assert_equal(url_os.path.normpath("aAbB//rel"), "aAbB//rel")
  assert_equal(url_os.path.normpath("/aAbB//root"), "/aAbB//root")
  assert_equal(url_os.path.normpath("//aAbB//root"), "//aAbB//root")
  assert_equal(url_os.path.normpath("//aAbB//root/."), "//aAbB//root/")
  assert_equal(url_os.path.normpath("//aAbB//root/.."), "//aAbB/")
  assert_equal(url_os.path.normpath("//aAbB//root/../.."), "//aAbB")
  assert_equal(url_os.path.normpath("//aAbB//root/../../.."), "/")
  assert_equal(url_os.path.normpath("//aAbB//root/../../../.."), "/")
  assert_equal(url_os.path.normpath("/."), "/")
  assert_equal(url_os.path.normpath("/.."), "/")
  assert_equal(url_os.path.normpath("//"), "//")
  assert_equal(url_os.path.normpath("//."), "//")
  assert_equal(url_os.path.normpath("//.."), "/")
