def test_xor__True_False(): assert_equal(xor(True, False), True)
def test_xor__False_True(): assert_equal(xor(False, True), True)
def test_xor__False_False(): assert_equal(xor(False, False), False)
def test_xor__True_True(): assert_equal(xor(True, True), None)
def test_xor__False_0(): assert_equal(xor(False, 0), 0)
def test_xor__None_False_0(): assert_equal(xor(None, False, 0), 0)
def test_xor__1_2(): assert_equal(xor(1, 2), None)
def test_xor__1_2_default(): assert_equal(xor(1, 2, default=False), False)
def test_xor__1_2_False(): assert_equal(xor(1, 2, False), False)
def test_xor__0_1_2(): assert_equal(xor(0, 1, 2), 0)
def test_xor__False_0_1_2(): assert_equal(xor(False, 0, 1, 2), 0)
def test_xor__1(): assert_equal(xor(1), 1)
def test_xor__1_0(): assert_equal(xor(1, 0), 1)
def test_xor__False_1_2(): assert_equal(xor(False, 1, 2), False)
def test_xor__1_False_0(): assert_equal(xor(1, False, 0), 1)
def test_xor__1_False_2(): assert_equal(xor(1, False, 2), False)
def test_xor__False_1_None_0(): assert_equal(xor(False, 1, None, 0), 1)
