# os_strerror.py Version 1.0.0-2
# Copyright (c) 2021 Tristan Cavelier <t.cavelier@free.fr>
# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://www.wtfpl.net/ for more details.

def os_strerror():

  def _generate_dict(os_module, errno_module, max_code=1000, indent="      "):
    # >>> print(os_strerror._generate_dict(os, errno))
    s = []
    for i in range(max_code):
      e = errno_module.errorcode.get(i)
      m = os_module.strerror(i)
      if not m.startswith("Unknown error"):
        if e is None:
          if i == 0: s.append(f"{indent}{i!r}: {m!r},\n")
          else: s.append(f"{indent}#{i!r}: {m!r},\n")
        else: s.append(f"{indent}{e!r}: {m!r},\n")
    s.sort()
    return "".join(s)

  def os_strerror(code, *, errno_module=None):
    if not isinstance(code, int): raise TypeError("an integer is required")
    if errno_module is None: errno_module = errno
    # here is a mix between python3.9 on win and python3.8 on linux _generate_dict results
    return {
      #0: 'No error',
      0: 'Success',
      #100: 'address in use',
      #101: 'address not available',
      #102: 'address family not supported',
      #103: 'connection already in progress',
      #106: 'connection aborted',
      #107: 'connection refused',
      #108: 'connection reset',
      #109: 'destination address required',
      #110: 'host unreachable',
      #112: 'operation in progress',
      #113: 'already connected',
      #114: 'too many symbolic link levels',
      #115: 'message size',
      #116: 'network down',
      #117: 'network reset',
      #118: 'network unreachable',
      #119: 'no buffer space',
      #123: 'no protocol option',
      #126: 'not connected',
      #128: 'not a socket',
      #130: 'operation not supported',
      #135: 'protocol not supported',
      #136: 'wrong protocol type',
      #138: 'timed out',
      #140: 'operation would block',
      #133: 'Memory page has hardware error',
      #'E2BIG': 'Arg list too long',
      'E2BIG': 'Argument list too long',
      'EACCES': 'Permission denied',
      'EADDRINUSE': 'Address already in use',
      'EADDRNOTAVAIL': 'Cannot assign requested address',
      'EADV': 'Advertise error',
      'EAFNOSUPPORT': 'Address family not supported by protocol',
      'EAGAIN': 'Resource temporarily unavailable',
      'EALREADY': 'Operation already in progress',
      'EBADE': 'Invalid exchange',
      'EBADF': 'Bad file descriptor',
      'EBADFD': 'File descriptor in bad state',
      #'EBADMSG': 'bad message',
      'EBADMSG': 'Bad message',
      'EBADR': 'Invalid request descriptor',
      'EBADRQC': 'Invalid request code',
      'EBADSLT': 'Invalid slot',
      'EBFONT': 'Bad font file format',
      #'EBUSY': 'Resource device',
      'EBUSY': 'Device or resource busy',
      #'ECANCELED': 'operation canceled',
      'ECANCELED': 'Operation canceled',
      'ECHILD': 'No child processes',
      'ECHRNG': 'Channel number out of range',
      'ECOMM': 'Communication error on send',
      'ECONNABORTED': 'Software caused connection abort',
      'ECONNREFUSED': 'Connection refused',
      'ECONNRESET': 'Connection reset by peer',
      'EDEADLOCK': 'Resource deadlock avoided',
      'EDESTADDRREQ': 'Destination address required',
      #'EDOM': 'Domain error',
      'EDOM': 'Numerical argument out of domain',
      'EDOTDOT': 'RFS specific error',
      'EDQUOT': 'Disk quota exceeded',
      'EEXIST': 'File exists',
      'EFAULT': 'Bad address',
      'EFBIG': 'File too large',
      'EHOSTDOWN': 'Host is down',
      'EHOSTUNREACH': 'No route to host',
      #'EIDRM': 'identifier removed',
      'EIDRM': 'Identifier removed',
      #'EILSEQ': 'Illegal byte sequence',
      'EILSEQ': 'Invalid or incomplete multibyte or wide character',
      'EINPROGRESS': 'Operation now in progress',
      #'EINTR': 'Interrupted function call',
      'EINTR': 'Interrupted system call',
      'EINVAL': 'Invalid argument',
      'EIO': 'Input/output error',
      'EISCONN': 'Transport endpoint is already connected',
      'EISDIR': 'Is a directory',
      'EISNAM': 'Is a named type file',
      'EKEYEXPIRED': 'Key has expired',
      'EKEYREJECTED': 'Key was rejected by service',
      'EKEYREVOKED': 'Key has been revoked',
      'EL2HLT': 'Level 2 halted',
      'EL2NSYNC': 'Level 2 not synchronized',
      'EL3HLT': 'Level 3 halted',
      'EL3RST': 'Level 3 reset',
      'ELIBACC': 'Can not access a needed shared library',
      'ELIBBAD': 'Accessing a corrupted shared library',
      'ELIBEXEC': 'Cannot exec a shared library directly',
      'ELIBMAX': 'Attempting to link in too many shared libraries',
      'ELIBSCN': '.lib section in a.out corrupted',
      'ELNRNG': 'Link number out of range',
      'ELOOP': 'Too many levels of symbolic links',
      'EMEDIUMTYPE': 'Wrong medium type',
      'EMFILE': 'Too many open files',
      'EMLINK': 'Too many links',
      'EMSGSIZE': 'Message too long',
      'EMULTIHOP': 'Multihop attempted',
      #'ENAMETOOLONG': 'Filename too long',
      'ENAMETOOLONG': 'File name too long',
      'ENAVAIL': 'No XENIX semaphores available',
      'ENETDOWN': 'Network is down',
      'ENETRESET': 'Network dropped connection on reset',
      'ENETUNREACH': 'Network is unreachable',
      'ENFILE': 'Too many open files in system',
      'ENOANO': 'No anode',
      'ENOBUFS': 'No buffer space available',
      'ENOCSI': 'No CSI structure available',
      #'ENODATA': 'no message available',
      'ENODATA': 'No data available',
      'ENODEV': 'No such device',
      'ENOENT': 'No such file or directory',
      'ENOEXEC': 'Exec format error',
      'ENOKEY': 'Required key not available',
      'ENOLCK': 'No locks available',
      #'ENOLINK': 'no link',
      'ENOLINK': 'Link has been severed',
      'ENOMEDIUM': 'No medium found',
      #'ENOMEM': 'Not enough space',
      'ENOMEM': 'Cannot allocate memory',
      #'ENOMSG': 'no message',
      'ENOMSG': 'No message of desired type',
      'ENONET': 'Machine is not on the network',
      'ENOPKG': 'Package not installed',
      'ENOPROTOOPT': 'Protocol not available',
      'ENOSPC': 'No space left on device',
      #'ENOSR': 'no stream resources',
      'ENOSR': 'Out of streams resources',
      #'ENOSTR': 'not a stream',
      'ENOSTR': 'Device not a stream',
      'ENOSYS': 'Function not implemented',
      'ENOTBLK': 'Block device required',
      'ENOTCONN': 'Transport endpoint is not connected',
      'ENOTDIR': 'Not a directory',
      'ENOTEMPTY': 'Directory not empty',
      'ENOTNAM': 'Not a XENIX named type file',
      #'ENOTRECOVERABLE': 'state not recoverable',
      'ENOTRECOVERABLE': 'State not recoverable',
      'ENOTSOCK': 'Socket operation on non-socket',
      #'ENOTSUP': 'not supported',
      'ENOTSUP': 'Operation not supported',
      #'ENOTTY': 'Inappropriate I/O control operation',
      'ENOTTY': 'Inappropriate ioctl for device',
      'ENOTUNIQ': 'Name not unique on network',
      'ENXIO': 'No such device or address',
      #'EOVERFLOW': 'value too large',
      'EOVERFLOW': 'Value too large for defined data type',
      #'EOWNERDEAD': 'owner dead',
      'EOWNERDEAD': 'Owner died',
      'EPERM': 'Operation not permitted',
      'EPFNOSUPPORT': 'Protocol family not supported',
      'EPIPE': 'Broken pipe',
      #'EPROTO': 'protocol error',
      'EPROTO': 'Protocol error',
      'EPROTONOSUPPORT': 'Protocol not supported',
      'EPROTOTYPE': 'Protocol wrong type for socket',
      #'ERANGE': 'Result too large',
      'ERANGE': 'Numerical result out of range',
      'EREMCHG': 'Remote address changed',
      'EREMOTE': 'Object is remote',
      'EREMOTEIO': 'Remote I/O error',
      'ERESTART': 'Interrupted system call should be restarted',
      'ERFKILL': 'Operation not possible due to RF-kill',
      'EROFS': 'Read-only file system',
      #'ESPIPE': 'Invalid seek',
      'ESHUTDOWN': 'Cannot send after transport endpoint shutdown',
      'ESOCKTNOSUPPORT': 'Socket type not supported',
      'ESPIPE': 'Illegal seek',
      'ESRCH': 'No such process',
      'ESRMNT': 'Srmount error',
      'ESTALE': 'Stale file handle',
      'ESTRPIPE': 'Streams pipe error',
      #'ETIME': 'stream timeout',
      'ETIME': 'Timer expired',
      'ETIMEDOUT': 'Connection timed out',
      'ETOOMANYREFS': 'Too many references: cannot splice',
      #'ETXTBSY': 'text file busy',
      'ETXTBSY': 'Text file busy',
      'EUCLEAN': 'Structure needs cleaning',
      'EUNATCH': 'Protocol driver not attached',
      'EUSERS': 'Too many users',
      #'EXDEV': 'Improper link',
      'EXDEV': 'Invalid cross-device link',
      'EXFULL': 'Exchange full',
    }.get(errno.errorcode.get(code, code), f"Unknown error {code}")

  os_strerror._generate_dict = _generate_dict
  return os_strerror

os_strerror = os_strerror()
os_strerror._required_globals = ["errno"]
